{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: argocd
spec:
  project: {{ .project | quote }}
  source:
    repoURL: {{ .repoURL | quote }}
    targetRevision: {{ .targetRevision | quote }}
    path: {{ .path | quote }}
    helm:
      releaseName: {{ .name | quote }}
  destination:
    server: {{ .destinationServer | quote }}
    namespace: {{ .destinationNamespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
