apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: "{{ .Values.config.DEBUG }}"
  DB_NAME: "{{ .Values.config.DB_NAME }}"
  DB_USER: "{{ .Values.config.DB_USER }}"
  DB_PASSWORD: "{{ .Values.config.DB_PASSWORD }}"
  DB_HOST: "{{ .Values.config.DB_HOST }}"
  DB_PORT: "{{ .Values.config.DB_PORT }}"